# Generated by Django 3.2 on 2022-02-18 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220217_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_event', models.DateTimeField()),
                ('event_site', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='products.category')),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
    ]
