# Generated by Django 3.2 on 2022-02-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='artista',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
