# Generated by Django 3.2 on 2022-02-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_artista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.AddField(
            model_name='event',
            name='status_event',
            field=models.CharField(choices=[('PRONTO', 'pronto'), ('PREVENTA', 'preventa'), ('DISPONIBLE', 'disponible'), ('AGOTADO', 'agotado'), ('SUSPENDIDO', 'suspendido')], default='PRONTO', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status_product',
            field=models.CharField(choices=[('DISPONIBLE', 'disponible'), ('AGOTADO', 'agotado')], default='DISPONIBLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
