# Generated by Django 3.2 on 2022-02-19 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20220219_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='event_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.event'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
