# Generated by Django 3.2 on 2022-02-21 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_event', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status_event', models.CharField(choices=[('PRONTO', 'pronto'), ('PREVENTA', 'preventa'), ('DISPONIBLE', 'disponible'), ('AGOTADO', 'agotado'), ('SUSPENDIDO', 'suspendido')], default='PRONTO', max_length=15, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('date_event', models.DateTimeField()),
                ('city', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('image_event', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_product', models.IntegerField()),
                ('quantity_event', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('id_event_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.event')),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ticket', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('id_event_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='products.event')),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tour', models.CharField(max_length=255)),
                ('artista', models.CharField(max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('tour_image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('slug', models.SlugField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='Ticket_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_order', to='products.order')),
                ('id_ticket_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_order', to='products.order')),
                ('id_product_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='event_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ticket'),
        ),
        migrations.AddField(
            model_name='order',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='product_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='event',
            name='id_tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='products.tour'),
        ),
    ]
