# Generated by Django 3.2 on 2022-02-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('EMPTY', 'empty'), ('PENDING', 'pending'), ('COMPLETED', 'completed')], default='EMPTY', max_length=25),
        ),
    ]
