# Generated by Django 3.2 on 2022-03-05 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='id_event_ticket',
            new_name='event',
        ),
    ]
