# Generated by Django 3.2 on 2022-02-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='event_order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity_event',
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity_product',
            field=models.IntegerField(null=True),
        ),
    ]
