# Generated by Django 3.2 on 2022-02-24 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220224_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.order')),
                ('id_product_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Product_Order',
        ),
    ]
