# Generated by Django 3.2 on 2022-02-27 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220224_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id_tour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='products.tour'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_event',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status_event',
            field=models.CharField(choices=[('SOON', 'soon'), ('PRESALE', 'presale'), ('AVAILABLE', 'available'), ('SOLD OUT', 'sold out'), ('CANCELLED', 'cancelled')], default='SOON', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('CREATED', 'created'), ('PENDING', 'pending'), ('PAID', 'paid'), ('COMPLETED', 'completed')], default='CREATED', max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tickets/'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='tickets/'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='artista',
            field=models.CharField(default='Dua Lipa', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_image',
            field=models.ImageField(blank=True, null=True, upload_to='tours/'),
        ),
    ]
