# Generated by Django 3.2 on 2022-02-27 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220227_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id_tour',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='products.tour'),
        ),
    ]
