# Generated by Django 3.2 on 2022-02-27 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_event_id_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id_event_product',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.event'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id_event_ticket',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='products.event'),
        ),
    ]
