# Generated by Django 3.2 on 2022-02-28 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20220227_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='artista',
            new_name='artist',
        ),
    ]
